name = "anquanpages"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

# 生产环境配置
[env.production]
vars = { ENVIRONMENT = "production" }

# 预览环境配置  
[env.preview]
vars = { ENVIRONMENT = "preview" }

# 构建配置
[[env.production.build]]
command = "npm run build"

[[env.preview.build]]
command = "npm run build" 